Migrate totalDebt before continous rewards
balancednetwork/balanced-java-contracts pull request #107
Opened 2022-05-19 08:58 UTC by AntonAndell

2022-05-19 12:43 UTC, nightowl121 commented
@AntonAndell Please fix the merge conflicts

2022-05-19 13:12 UTC, nightowl121 requested changes

2022-05-19 13:12 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        if (currentDay.get().compareTo(day) < 0 && day.compareTo(continuousRewardDay.get()) < 0) {
continuous reward day should be handled here for being null.

2022-05-19 13:12 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/PositionsDB.java
> +
Use BNUSD_SYMBOL constant instead of exact string.

2022-05-19 13:12 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
> +            LoansVariables.totalDebts.set(symbol, newTotalDebt);
Isn't the value coming here as a complete new value rather than incremental value.

2022-05-19 13:35 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
> +            LoansVariables.totalDebts.set(symbol, newTotalDebt);
Also, the debt value should only be increased if the asset is not collateral.

2022-05-19 13:43 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
> +            LoansVariables.totalDebts.set(symbol, newTotalDebt);
Active assets are just the debt so should only be debt. The value is new but it does overwrite so there can be previous debt. But should only be removed if it has already been added. Which is not the case now so that needs to be fixed

2022-05-23 18:05 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java
> +            LoansVariables.totalDebts.set(symbol, newTotalDebt);
So this does no longer apply? 
https://github.com/balancednetwork/balanced-contracts/blob/6a3e4d01ef43483eaf6619dd91ef582f22e56dec/core_contracts/loans/loans/assets.py#L202

there are probably a few bugs in this contract if this is false on mainnet

2022-05-23 18:12 UTC, nightowl121 commented
Nevermind, you can ignore the comment. I confused with the variables.

-------- Original Message --------
On May 23, 2022, 11:50 PM, AntonAndell wrote:

> @AntonAndell commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/Position.java](https://github.com/balancednetwork/balanced-java-contracts/pull/107#discussion_r879742426):
>
>> +            BigInteger previousTotalDebt = LoansVariables.totalDebts.getOrDefault(symbol, BigInteger.ZERO);
> +            BigInteger newTotalDebt = previousTotalDebt.subtract(previousDebt).add(value);
> +            LoansVariables.totalDebts.set(symbol, newTotalDebt);
>
> So this does no longer apply?
> https://github.com/balancednetwork/balanced-contracts/blob/6a3e4d01ef43483eaf6619dd91ef582f22e56dec/core_contracts/loans/loans/assets.py#L202
>
> there are probably a few bugs in this contract if this is false on mainnet
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/balancednetwork/balanced-java-contracts/pull/107#discussion_r879742426), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AV5FZODE5HQCCCCG5I5P2ADVLPCHVANCNFSM5WLPA7SA).
> You are receiving this because your review was requested.Message ID: ***@***.***>

2022-05-25 05:36 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        Context.require(badDebt.compareTo(_value) >= 0, TAG + ": No bad debt for " + _symbol);
This avoids partial payment of bad debt. Previously in python contract we had `bad_debt <= 0` as a failure condition or `bad_debt > 0` as success condition. Now we are changing it to be `badDebt >= _value`. [L507](https://github.com/balancednetwork/balanced-java-contracts/pull/107/files#diff-a712140b8a1c3c1b804a9f575a869c523d0fcf224c44146742f7d1871a4de686R507) make sure that minimum value is chosen but now the lowest value is existing bad debt amount.

2022-05-25 05:49 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/positions/PositionsDB.java
> -        if (isBeforeContinuousRewardDay(snapshotIndex.intValue())) {
Lets reuse snapshot index/ current day here, that would decrease the DB read count resulting in less fees.

2022-05-25 05:58 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        Context.require(badDebt.compareTo(_value) >= 0, TAG + ": No bad debt for " + _symbol);
im not sure if i follow. what behavior do we want for bad debt? I see in the python contract we just checked that badDebt wasnt zero. Is that the check we want instead?

so Context.require(badDebt.compareTo(BigInteger.ZERO) > 0, "No bad debt for " + _symbol);

2022-05-25 06:15 UTC, nightowl121 commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        Context.require(badDebt.compareTo(_value) >= 0, TAG + ": No bad debt for " + _symbol);
Sorry about the confusion. Yes the actual behavior should be checking with 0. Checking with value limits one condition.

Example: If the bad debt is 1000, I can't specify value as 1001. Previously it used to work by burning 1000 and leaving the 1. This requires user to precisely provide the bad debt amount rather than providing a big value and utilizing only what's required.

2022-05-25 06:25 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        Context.require(badDebt.compareTo(_value) >= 0, TAG + ": No bad debt for " + _symbol);
Okey yeah i see. Thanks!

2022-05-25 06:30 UTC, merged