Add accrued fees database to fee handler
balancednetwork/balanced-java-contracts pull request #173
Opened 2022-07-08 22:04 UTC by BennyOptions

Creates a database to store accrued fees from various sources. Updates token fallback method to add all fees to the accrued fees database

2022-07-11 07:55 UTC, nightowl121 requested changes

2022-07-11 07:55 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +    private final DictDB<Address, BigInteger> swapFeesAccruedDB = Context.newDictDB(DIVIDEND_TOKENS, BigInteger.class);
Its better to use different key, since keeping same keys might mix with the other database. Although the database type is different which should avoid any issues, but its better to be safe by creating different keys.

2022-07-11 07:55 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +    private BigInteger stabilityFundFeesAccrued;
Both of these should be stored in DB for persistence. This will work though until there is next score update.

2022-07-11 07:55 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        for (int i = 0; i < acceptedDividendsTokens.size(); i++) {
size should be read once and stored in a local variable otherwise the cost is increased by `number of loop` times

2022-07-11 07:55 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +    }
this method might not be required.

2022-07-11 07:55 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +            BigInteger accruedFees = swapFeesAccruedDB.get(sender);
Use getOrDefault while getting value from `swapFeesAccruedDB` as it can give Null Pointer Exception.

2022-07-11 08:05 UTC, AntonAndell commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +            BigInteger accruedFees = swapFeesAccruedDB.get(sender);
There is a null check above which makes sense, since all fee from dex should not be in the DB

2022-07-11 08:05 UTC, AntonAndell commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +            swapFeesAccruedDB.set(thisToken, swapFeesAccruedDB.get(thisToken));
```suggestion
            swapFeesAccruedDB.set(thisToken, swapFeesAccruedDB.getOrDefualt(thisToken, BigInteger.ZERO));
```

2022-07-11 08:08 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +    }
Changed the logic to store the default value and if dictdb is null then the token should not be tracked for fees.

2022-07-11 08:08 UTC, AntonAndell commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        if (_from == loans.get()) {
For all these ifs, use if, else if to save some gas. Also change compares to use .equals. 
```suggestion
        if (_from.equals(loans.get())) {
```

2022-07-11 08:08 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +            BigInteger accruedFees = swapFeesAccruedDB.get(sender);
Yeah modified the logic with new update.

2022-07-11 08:11 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        if (_from == loans.get()) {
Fixed for all address comparisons.

2022-07-11 08:18 UTC, AntonAndell commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        }
Since this affect basically all transactions we should optimize gas a little
```suggestion
        if (_from.equals(dex.get())) {
            BigInteger accruedFees = swapFeesAccruedDB.get(sender);
            if (accuredFees == null) {
                return;
            }
            
            swapFeesAccruedDB.set(sender, accruedFees.add(_value));
            return;
        }
        
        if (_from.equals(loans.get())) {
            loanFeesAccrued.set(loanFeesAccrued.getOrDefault(BigInteger.ZERO).add(_value));
            return;
        }
    
        if (_from.equals(stabilityFund.get())) {
            stabilityFundFeesAccrued.set(stabilityFundFeesAccrued.getOrDefault(BigInteger.ZERO).add(_value));
            return;
        }
```

2022-07-11 08:49 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        }
Better to use if-else ladder or switch.

2022-07-12 05:29 UTC, nightowl121 approved these changes
LGTM

2022-07-12 05:29 UTC, merged