Governance voting changes caused by boosted baln
balancednetwork/balanced-java-contracts pull request #175
Opened 2022-07-11 07:06 UTC by simusud

governance voting changes caused by boosted baln 
updated unit tests for governance voting

2022-07-11 07:45 UTC, AntonAndell commented on core-contracts/Governance/src/main/java/network/balanced/score/core/governance/GovernanceImpl.java
> +        if (proposal.startSnapshot.get().compareTo(BigInteger.valueOf(Context.getBlockHeight())) <= 0) {
@nightowl121 wont bBaln adhere to timeOffset? If not perhaps we should add a setTimeOffset to bBaln. Could make some integration tests possible aswell

2022-07-11 10:30 UTC, AntonAndell commented
We will also change the define vote signature in this PR https://github.com/balancednetwork/balanced-java-contracts/pull/162

So we could combine them if we wanna do any other changes to the function parameters

2022-07-11 17:21 UTC, dbrehmer commented
Add forum link issue to this work #26 
See notes on issue #29 as well.

2022-07-28 10:37 UTC, AntonAndell requested changes
Looks good, just some small changes then it is probably fine to merge into the bBaln branch

2022-07-28 10:37 UTC, AntonAndell commented on core-contracts/Governance/src/main/java/network/balanced/score/core/governance/GovernanceImpl.java
> +        BigInteger currentBlockHeight = BigInteger.valueOf(Context.getBlockHeight());
```suggestion
```

2022-07-28 10:37 UTC, AntonAndell commented on core-contracts/Governance/src/main/java/network/balanced/score/core/governance/ProposalDB.java
>          newProposal.endSnapshot.set(end);
Think it is time to rename these variables, something like
snapshotBlock
startDay
endDay
No need to change the strings keys in checkVote though

2022-07-28 10:37 UTC, AntonAndell commented on core-contracts/Governance/src/test/java/network/balanced/score/core/governance/GovernanceTestBase.java
> +
```suggestion
```

2022-07-28 10:37 UTC, AntonAndell commented on core-contracts/Governance/src/test/java/network/balanced/score/core/governance/GovernanceVotingTest.java
> +        ;
```suggestion
```

2022-07-28 10:37 UTC, AntonAndell commented on core-contracts/Governance/src/test/java/network/balanced/score/core/governance/GovernanceVotingTest.java
> +        ;
```suggestion
```

2022-09-19 11:11 UTC, nightowl121 approved these changes
Approved

2022-09-19 11:11 UTC, merged