Rewrite dividends calculation to be based on bbaln
balancednetwork/balanced-java-contracts pull request #183
Opened 2022-07-20 03:44 UTC by ZeChosenName

2022-08-04 08:07 UTC, AntonAndell commented
We need handle the migration here properly, the time between where staked baln/last claimed to boosted launch will be unaccounted for since your previous boosted balance was 0. But we cannot either use the old staked balance as previous since the total supplies wont add up.

2022-09-20 05:42 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        DividendsTracker.setBBalnTotalSupply(getBoostedTotalSupply().add(bBalnBalance));
We also need to subtract previous here

2022-09-21 04:57 UTC, AntonAndell requested changes

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +
Lets ignore switching day.
Lets make it so that bBaln is used directly on deployment

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +
This also will entail that you don't have to separate it into two different weights

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        Context.require(Context.getCaller().equals(boostedBalnScore.get()), TAG + " Only BBaln contract is allowed to" +
can use only(boostedBalnScore) here

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        Context.require(Context.getCaller().equals(boostedBalnScore.get()), TAG + " Only BBaln contract is allowed to" +
can user only(boostedBalnScore) here

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        userBalance.set(user, getBoostedBalnBalance(user));
No need to fetch 0 can be assumed on a kick

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/test/java/network/balanced/score/core/dividends/DividendsImplTestContinuousDividends.java
> +//        dividendScore.invoke(owner, "setContinuousDividendsDay", day.add(BigInteger.ONE));
remove

2022-09-21 04:57 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void claimDividends() {
We should also update a users boosted Balance after they have claimed. to keep it as recent as possible

2022-09-21 10:54 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +
No it can be emptied for now, but keep the function to avoid errors if called by the baln token

2022-09-21 12:19 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +
Might have jumped the gun here it might still be needed to handle the switch properly. So people do not loose any unclaimed divs

2022-09-22 05:17 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void updateBalnStake(Address user, BigInteger prevStakedBalance, BigInteger currentTotalSupply) {
I realized we can keep this as is instead pretty much, so we catch people unstaking to go into bBaln. So when people claim or unstake all the non boosted dividends are claimed. You can have your null check in here as well though.

2022-09-22 05:18 UTC, AntonAndell commented
Looks pretty finished now just 2 comments that needs to be addressed. Then just double check code formatting and that the tests are up to date

2022-09-22 06:10 UTC, Suyog007 commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void claimDividends() {
I assume by updating a user boosted balance here means setting the current boosted balance of the user and reducing the total supply of a bbaln again ?

2022-09-22 06:11 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void claimDividends() {
Yeah after they have claimed

2022-09-22 06:41 UTC, Suyog007 commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void updateBalnStake(Address user, BigInteger prevStakedBalance, BigInteger currentTotalSupply) {
there may be a case where a user may boost their free baln token instead of unstaking a balance token and boosting it. 
In that case , while claiming their dividends they will get the dividends of previously staked baln as well as newly boosted baln , and we will be setting their previous weight to null . 
And if that same user unstakes now then he may get an issue due to null in their user weight.

2022-09-22 06:46 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void updateBalnStake(Address user, BigInteger prevStakedBalance, BigInteger currentTotalSupply) {
Yeah we will need to check if it is already null in the UpdateBalnStake and if so just ignore. So you accrue your old divs by either unstaking or claiming. And after that baln should be ignored

2022-09-22 06:47 UTC, Suyog007 commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
>      public void updateBalnStake(Address user, BigInteger prevStakedBalance, BigInteger currentTotalSupply) {
condition added in the latest commit

2022-09-29 06:03 UTC, merged