added sellCollateral method on loans
balancednetwork/balanced-java-contracts pull request #227
Opened 2022-09-11 13:10 UTC by simusud

Added sell collateral functionality and tests for same.

2022-09-12 05:57 UTC, AntonAndell requested changes
Good job with testing. 
Mainly minor comments, just missing the updating of rewards data

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        String collateralSymbol = optionalDefault(_collateralSymbol, SICX_SYMBOL);
Is not needed since this is a new function. This method of defining collateral symbol was made mainly to be backwards compatible with old functions

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        byte[] data = swapData.toString().getBytes();
Formatting here could be improved a little
```suggestion

        JsonObject swapParams = Json.object()
            .add("toToken", assetAddress.toString())
            .add("minimumReceive", minimumDebtToRepay.toString());
        JsonObject swapData = Json.object()
            .add("method", "_swap")
            .add("params", swapParams);
        byte[] data = swapData.toString().getBytes();
        
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        BigInteger poolID = Context.call(BigInteger.class, dex.get(), "getPoolId", collateralAddress, assetAddress);
Fetch dex once and save it. reduces gas cost slighlty

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +    private void sellUserCollateral(Address from, BigInteger collateralToSell, String collateralSymbol, BigInteger minimumDebtToRepay) {
Rewards data needs to be updated since debt is decreasing

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        position.setDebt(collateralSymbol, assetSymbol, remainingDebt);
if remainingDebt is 0 it has to be set to null, check return asset function for reference

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
> +        // Assert & Act
```suggestion
        takeLoanICX(account, "bnUSD", collateral, loan);
     
        // Assert & Act
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
> +        // Assert & Act
```suggestion
        takeLoanICX(account, "bnUSD", collateral, loan);
       
        // Assert & Act
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
> +        // Assert & Act
```suggestion
        takeLoanICX(account, "bnUSD", collateral, loan);
       
        // Assert & Act
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
> +
```suggestion
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/test/java/network/balanced/score/core/loans/LoansTest.java
> +
```suggestion

// Assert
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTest.java
> +        //  assert
```suggestion
        //  Assert
```

2022-09-12 05:57 UTC, AntonAndell commented on core-contracts/Loans/src/intTest/java/network/balanced/score/core/loans/LoansIntegrationTest.java
> +        assertEquals(loanTakerETHPartialDebtSellCollateralPost, loanTakerETHPartialDebtSellCollateralPre.subtract(ETHCollateralToSellPartialDebt));
Perhaps we should also assert that their debt also has decreased

2022-09-13 11:35 UTC, simusud commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        BigInteger poolID = Context.call(BigInteger.class, dex.get(), "getPoolId", collateralAddress, assetAddress);
Did you mean dex.get() ? It is only used here in this method, though we need to fetch it once if we store as well .

2022-09-13 11:59 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +        transferCollateral(collateralSymbol, dex.get(), collateralToSell,
https://github.com/balancednetwork/balanced-java-contracts/pull/227/files/43e2f914364256f88b6858460be0243f82a19845#r969507787
dex.get is also used here :slightly_smiling_face:

2022-09-14 09:11 UTC, simusud commented
Integration test for sellCollateral is success in my local env. But it seems to fail here...

2022-09-14 10:03 UTC, nightowl121 commented
> Integration test for sellCollateral is success in my local env. But it seems to fail here...

This failure is due to skip transaction. Solution to this issue is to retry failed tests.

2022-09-14 10:03 UTC, AntonAndell reviewed
For integration test to pass you can try commenting out the migration part or integration tests. Is not needed anymore since multicollateral is on mainnet

2022-09-14 10:03 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
> +            debtSold = userDebt;
Think debtSold variable is unnecessary, just use assetRecived all the way. Since if they differ something will be very wrong

2022-09-27 06:34 UTC, AntonAndell approved these changes
LGTM
Will deploy and test on berlin

2022-09-28 16:07 UTC, AntonAndell approved these changes

2022-09-28 16:12 UTC, merged