slippage control while adding liquidity on Dex contract
balancednetwork/balanced-java-contracts pull request #392
Opened 2024-03-05 10:00 UTC by TRSSMG

2024-03-05 11:02 UTC, AntonAndell requested changes
Define default supply slippage as a constant along with other dex constants. 
For 10000 use global constant POINTS 
For checking default there should be a function optionalDefault in Checks library.

BigInteger default is 0 so null checks would not work in this case.
However this might be a problem if someone wants to supply with ZERO slippage. @nightowl121 Do you think we should default to Zero instead?

2024-03-06 07:57 UTC, nightowl121 commented
Yeah, I think the default value should be 0%. If a user supplies 0% or defaults to 0%, both means that users wants an exact price while adding LP tokens which may or may not be possible.

2024-03-06 08:46 UTC, AntonAndell commented
Okey so no need for default slippage. default will be 0 if a optional BigInteger is omitted. So it is fine to just use that directly

2024-03-07 12:09 UTC, AntonAndell requested changes
Looks good, just a few comments. Don't forget to check formatting

2024-03-12 06:07 UTC, AntonAndell requested changes
Looks good, just two minor changes

2024-03-12 06:07 UTC, AntonAndell commented on core-contracts/DAOfund/src/main/java/network/balanced/score/core/daofund/POLManager.java
> +        Context.call(dex, "add", baseAddress, quoteAddress, baseAmount, quoteAmount, true, getPOLSupplySlippage());
Remove the above logic that no longer is needed, that is manually checking slippage

2024-03-12 06:07 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +
```suggestion
```

2024-03-14 06:00 UTC, AntonAndell approved these changes

2024-03-14 06:01 UTC, merged