Router: stability fund swap implementation
balancednetwork/balanced-java-contracts pull request #411
Opened 2024-03-21 12:26 UTC by TRSSMG

2024-04-11 07:54 UTC, nightowl121 approved these changes
Approved

2024-04-12 09:26 UTC, AntonAndell requested changes
Route v2 also need to be a option in tokenFallback

2024-04-22 07:31 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        if (!params.contains("isStableSwap")) {
Instead use the method field here.
Switch on method and default revert.
"_swap"
and maybe 
"_swapv2"

No need for the extra parameter

2024-04-23 18:40 UTC, AntonAndell reviewed
Looks good, just one minor comment for now. WIll take another look tomorrow

2024-04-23 18:40 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        Context.require(routeData.method.contains("_swapV2"), TAG + ": Fallback directly not allowed.");
Do we need a method at all here?

2024-04-24 05:46 UTC, TRSSMG commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        Context.require(routeData.method.contains("_swapV2"), TAG + ": Fallback directly not allowed.");
ya, I think, separation is better

2024-04-24 05:50 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        Context.require(routeData.method.contains("_swapV2"), TAG + ": Fallback directly not allowed.");
How do you mean separation? What does the extra string "_swapv2" add information wise?

I can perhaps see if we want to add more methods in the future. But we already have actions for that

2024-04-26 06:40 UTC, TRSSMG commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>              return;
this also should be revert, other wise the token transfer will be success, while underlying reason for transfer will not execute

2024-04-26 06:41 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>              return;
No, this we need to accept deposits during the route. Only if someone tries to reenter(which they should not be able to) the will simply lose their deposit

2024-04-26 07:20 UTC, TRSSMG commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>              return;
ok, got it

2024-05-02 04:58 UTC, AntonAndell approved these changes

2024-05-02 04:58 UTC, merged