Balance worker token translated, and uni test written
balancednetwork/balanced-java-contracts pull request #43
Opened 2022-02-07 13:12 UTC by ZeChosenName

2022-02-09 16:42 UTC, nightowl121 requested changes
This is a partial review. Please check the changes requested.

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/build.gradle
> +version 'unspecified'
specify version here

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/WorkerToken.java
> +    public WorkerToken(Address _governance){
Make this `_governance` parameter optional, such that while updating contract we can simply skip this parameter.

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/WorkerToken.java
> +    public WorkerToken(Address _governance){
Also check if `_governance` is null (default value), do not perform the setter options. Basically we want to avoid writing to database if we have already written in the previous installation process and skip in the update process.

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/WorkerToken.java
> +    private VarDB<Address> baln_token = Context.newVarDB(BALN_TOKEN, Address.class);
Use camelCase naming convention for the variable

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/tokens/IRC2.java
> +    public void _transfer(Address _from, Address _to, BigInteger _value, byte[] _data) {
You can rename transfer method name adhering to [Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/WorkerToken.java
> +}
Simplify if...else condition.
Your code can be simplified to
```java
Context.require(Context.getCaller().equals(baln_token.get()), "error message");
baln.set(baln.getOrDefault(BigInteger.ZERO).add(_value));
```

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/tokens/IRC2.java
> +    protected VarDB<BigInteger> total_supply = Context.newVarDB(TOTAL_SUPPLY, BigInteger.class);
Naming convention

2022-02-09 16:42 UTC, nightowl121 commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/tokens/IRC2.java
> +        BigInteger DEFAULT_DECIMAL_VALUE = BigInteger.valueOf(0x12);
Can be created as `BigInteger.valueOf(18L)`

2022-02-11 07:03 UTC, ZeChosenName commented on token-contracts/bwt/src/main/java/network/balanced/score/tokens/tokens/IRC2.java
> +        BigInteger DEFAULT_DECIMAL_VALUE = BigInteger.valueOf(0x12);
I have changed the code as you requested.

2022-04-13 07:16 UTC, nightowl121 approved these changes
Looks good for deployment

2022-04-13 08:23 UTC, merged