feat: soft liquidation
balancednetwork/balanced-java-contracts pull request #438
Opened 2024-07-31 09:32 UTC by Itshyphen

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2024-08-02 06:32 UTC, AntonAndell requested changes
Other than threshold -> ratio and testing the PR looks good :+1: 
Will review calculations after the change

2024-08-08 04:58 UTC, gcranju commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansVariables.java
> -    private static final String LIQUIDATION_RATIO = "liquidation_ratio";
@AntonAndell made changes!

2024-08-09 07:37 UTC, AntonAndell requested changes
Looks good, just one pretty minor thing

2024-08-09 07:37 UTC, AntonAndell commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
>          }
We could add a check to see that remaining collateral is not below 0 since that is not a valid state.

Also if remaining debt is 0 it should be set to null same with remaining collateral. So these cases might need to be split up to be more granular

2024-08-09 07:46 UTC, gcranju commented on core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java
>          }
Here, we calculate spendable amount first and with that collateral to liquidate is calculated, precision makes it like remaining collateral can be in like -1000(10^-15), so considering that as zero with this check, so we can have negative remaining collateral here

2024-08-12 09:47 UTC, AntonAndell approved these changes

2024-09-23 11:03 UTC, AntonAndell approved these changes

2024-09-23 11:03 UTC, merged