feat: sicx/balan token crosschain
balancednetwork/balanced-java-contracts pull request #455
Opened 2024-10-04 09:13 UTC by Itshyphen

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2024-10-07 05:56 UTC, AntonAndell requested changes
Generally i think this looks correct.
We should add this logic as well for now. So we can do bridging from any chain to any chain.  
    @Override
    public BigInteger getHopFee(String net) {
        if (!canWithdraw(net)) {
            return BigInteger.ONE.negate();
        }
        return Context.call(BigInteger.class, getDaofund(), "claimXCallFee", net, false);
    }

    private boolean canWithdraw(String net) {
        return Context.call(Boolean.class, getDaofund(), "getXCallFeePermission", Context.getAddress(), net);
    }

2024-10-07 05:56 UTC, AntonAndell commented on token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/BalancedTokenImpl.java
> +        return minter.get();
How come this is added?

2024-10-07 06:03 UTC, gcranju commented on token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/BalancedTokenImpl.java
> +        return minter.get();
This was in IRC2Mintable, and we were using 'minter' to mint and burn those tokens, so need to add there

2024-10-08 03:48 UTC, Itshyphen commented
> Generally i think this looks correct. We should add this logic as well for now. So we can do bridging from any chain to any chain.
> 
> ```
>     @Override
>     public BigInteger getHopFee(String net) {
>         if (!canWithdraw(net)) {
>             return BigInteger.ONE.negate();
>         }
>         return Context.call(BigInteger.class, getDaofund(), "claimXCallFee", net, false);
>     }
> 
>     private boolean canWithdraw(String net) {
>         return Context.call(Boolean.class, getDaofund(), "getXCallFeePermission", Context.getAddress(), net);
>     }
> ```

yeahh, done

2024-10-17 07:42 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java
> +    public final static String BALN = "v1.1.2";
change versions to 1.1.0. Since we bumped a whole version.
Otherwise we can continue with launch

2024-10-17 08:00 UTC, AntonAndell approved these changes

2024-10-17 08:01 UTC, merged