Feature/crosschain lp
balancednetwork/balanced-java-contracts pull request #456
Opened 2024-10-08 14:30 UTC by TRSSMG

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2024-10-17 07:35 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        }
I think here we need to go a bit more complex unfortunately. We need to either withdraw via assetManager or xTransfer if the address is not a ICON one

2024-10-17 07:39 UTC, AntonAndell commented
What do you think creating a library like XCallLib but for token transfers? So that you can just call that in any contract. Which will query the daofund for the fee, check if token is in assetManager else use xTransfer.

2024-10-29 06:23 UTC, AntonAndell requested changes

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
>      public BigInteger depositOfUser(Address _owner, Address _token) {
replace to string owner.
If no other contracts address can be replaced with string quite easily. For frontend address and string is the same

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        //activeAddresses.get(id).add(from);
You can remove i think

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/IRC31StandardSpokeLpToken.java
> +        Context.call(contractAddress, "onIRC31Received", _from.toString(), _from.toString(), _id, _value, dataBytes);
Here it has to get a bit complicated to work with all contract. 
If from is a ICON address use the old onIRC31Received
If its a networkAddress user onXIRC31Received

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/IRC31StandardSpokeLpToken.java
> +        HubTransfer(BigInteger.valueOf(_id), _from.toString(), _to.toString(), _value, dataBytes);
Here is not a HubTransfer, This is where the Transfer single event is raised, And where we want to raise a HubTransferSingle

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> +    public void TransferSingle(String _operator, String _from, String _to, BigInteger _id, BigInteger _value) {
Look at comment in irc31 spoke. This can be removed here and create a HubTransferSingle in that code.

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Dex/src/test/java/network/balanced/score/core/dex/DexTestSettersAndGetters.java
> +//    }
I'd say remove

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Reserve/src/test/java/network/balanced/score/core/reserve/ReserveFundTest.java
You know what, just remove the whole reservefund contract. It is deprecated since last vote. So we dont need it more

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>          BigInteger balance = (BigInteger) Context.call(currentToken, "balanceOf", Context.getAddress());
We can remove all toNative logic, we should not support it anymore

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>          BigInteger balance = (BigInteger) Context.call(currentToken, "balanceOf", Context.getAddress());
And that should cleanup the logic very well

2024-10-29 06:23 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +    public void onIRC31Received(String _operator, String _from, BigInteger _id, BigInteger _value, byte[] _data) {
here also add the xVariant and keep both verision

2024-10-29 06:23 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/interfaces/base/IRC31Base.java
> -    void TransferSingle(Address _operator, Address _from, Address _to, BigInteger _id, BigInteger _value);
This needs to stay, just because this is the IRC31 standard

2024-10-29 06:23 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/TokenTransfer.java
> +    public static void transfer(Address token, String to, BigInteger amount, boolean toNative, byte[] data){
remove  boolean toNative, should make i a little cleaner

2024-10-29 06:23 UTC, AntonAndell commented on token-contracts/BalancedToken/src/main/java/network/balanced/score/tokens/balancedtoken/BalancedTokenImpl.java
> +import network.balanced.score.lib.tokens.HubTokenImpl;
Why is there a bunch of changes to this? arent they already on main?
Or did you just do this additional cleanup?

2024-10-30 06:05 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/interfaces/tokens/XReceiver.java
> +/*
Can be cleanuped if not used. Might be good to add the onXIRC31... as a interface so that its implemented the same in all contracts that use it

2024-10-30 09:10 UTC, TRSSMG commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> +    }
Ya, to support a call using native icon address keeping both version would be good I think

2024-10-30 09:11 UTC, TRSSMG commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> -
ya this is just moved to IRC31StandardSpokeLpToken

2024-10-30 09:12 UTC, TRSSMG commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
>          BigInteger balance = (BigInteger) Context.call(currentToken, "balanceOf", Context.getAddress());
all toNative logic has been removed

2024-11-04 07:40 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
>              withdraw(_baseToken, userDepositedBase);
I think this is wrong, this withdraws to caller

2024-11-04 07:41 UTC, AntonAndell reviewed
Can we make "to" paramerete optional id xTokenFallback deposit?

2024-11-19 06:24 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> +    }
This i what this would do
NetworkAddress user = new NetworkAddress(NATIVE_NID, _user);

But we can keep aswell

2024-11-20 07:19 UTC, AntonAndell requested changes

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        }
We should use token transfer lib here?

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
>      public BigInteger depositOfUser(Address _owner, Address _token) {
+

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        Context.println("value is: "+value);
```suggestion

```

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        Context.require(value.compareTo(BigInteger.ZERO) > 0, "StakedLP: Cannot unstake less than zero value");
```suggestion
```

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        NetworkAddress from = NetworkAddress.valueOf(_from.toString(), NATIVE_NID);
SHould use new here i think

2024-11-20 07:19 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        }
What is user.account?
this should not need a change?

2024-11-20 07:19 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/TokenTransfer.java
> +package network.balanced.score.lib.utils;
Some unit tests for this would be good

2024-11-20 11:38 UTC, TRSSMG commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        }
This (user.account()) is for icon addresses, there are cases that balance and supply is updated with icon addresses instead of network address. Sending the network address from here won't catch the previous balances where icon address is used.

2024-11-20 11:38 UTC, TRSSMG commented on score-lib/src/main/java/network/balanced/score/lib/utils/TokenTransfer.java
> +package network.balanced.score.lib.utils;
tests added

2024-11-20 11:48 UTC, AntonAndell commented on core-contracts/StakedLP/src/main/java/network/balanced/score/core/stakedlp/StakedLPImpl.java
> +        }
Right yeah since it uses networkAddress

2024-11-21 07:59 UTC, AntonAndell requested changes

2024-11-21 07:59 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> +
```suggestion


```

2024-11-21 07:59 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
>      public BigInteger depositOfUser(Address _owner, Address _token) {
Is there any reason this is not the case? or is there a v2 somewhere?

2024-11-21 07:59 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/IRC31StandardSpokeLpToken.java
> +        Context.call(contractAddress, "onXIRC31Received", _from.toString(), _from.toString(), _id, _value, dataBytes);
Hmm annoying but if the from is a ICON address to stay compatible we need to use the old onIRC31Received instead.

2024-11-22 07:01 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/TokenTransfer.java
> +       NetworkAddress toNetworkAddress = NetworkAddress.parse(to);
Should probably be valueOf

2024-11-29 07:56 UTC, AntonAndell approved these changes

2024-11-29 07:56 UTC, merged