Feat/crosschain savings
balancednetwork/balanced-java-contracts pull request #467
Opened 2024-11-29 09:37 UTC by TRSSMG

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2024-12-18 07:35 UTC, AntonAndell requested changes
Most code could need some formatting, otherwise just a few small comments

2024-12-18 07:35 UTC, AntonAndell commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +    }
Why was this added?

2024-12-18 07:35 UTC, AntonAndell commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +        if(json.get("params")!=null) {
use contains to check if it has

2024-12-18 07:35 UTC, AntonAndell commented on crosschain_savings.md
> +## Crosschain Savings Feature Implementation Steps
Could use double checking of formatting

2024-12-18 07:35 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/Versions.java
> +    public final static String SICX = "v1.1.0";
?

2024-12-18 07:35 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +            routeData = RouteData.fromBytesOld(data);
Can we get a unit test for this. You can just import the writer into a unit test and manually encode a old route

2024-12-18 07:35 UTC, AntonAndell commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        if(params.get("data")!=null){
contains

2024-12-18 07:46 UTC, TRSSMG commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +    }
Daofund contract wants to transfer icx to the savings contract to pay the fee for xcall?!

2024-12-18 07:57 UTC, AntonAndell commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +    }
Right yeah, forgot the logic now that it is abstrascted in the token lib

2024-12-18 08:37 UTC, TRSSMG commented on crosschain_savings.md
> +## Crosschain Savings Feature Implementation Steps
revised and fixed

2025-01-27 02:59 UTC, ibrizsabin commented on core-contracts/Router/src/main/java/network/balanced/score/core/router/RouterImpl.java
> +        }
we can assign data to EMPTY_BYTES here itself so that we wont need to check that again later.

2025-01-27 03:02 UTC, ibrizsabin commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +        RewardsManager.changeLock(user, amount.negate());
instead of doing amount.negate() it would be better to explicitly subtract the amount in changeLock ?

2025-01-27 06:27 UTC, AntonAndell commented on core-contracts/Savings/src/main/java/network/balanced/score/core/savings/SavingsImpl.java
> +        RewardsManager.changeLock(user, amount.negate());
I think reusing changeLock instead, which i think is fine.

2025-02-03 06:18 UTC, AntonAndell approved these changes

2025-02-03 06:18 UTC, merged