(Re)adding initial rebalancing changes
balancednetwork/balanced-java-contracts pull request #54
Opened 2022-02-15 03:09 UTC by addouglas

Still needs tests but has a few updates to address constructor and removal of a sICX Receivables VarDB entry that was previously only removed on update. If we see a need to add back the removal, please let me know.

2022-02-15 06:27 UTC, addouglas commented
I'm trying to figure out the "why" behind the way admin and governance states/properties were setup in the original rebalancing contract and why so few "get" methods were included in the original. Not sure the best place to ask the question - basically it's odd so I made some tweaks to bring it inline with other contracts... but I can match it 1 for 1 if you'd prefer.

In the original python code - on_install is setting *admin* to governance address which is passed in. I confirmed that governance was in fact what was called on the initial creation of the contract. But it sets admin to the governance value passed in and there's no way to set admin. So all the checks in the original for owner are logically actually being checked against governance as far as I can tell. Also, there are essentially no "gets" for any of these state values. It's like we wanted them secret even though other contracts expose them (more or less). Note: I'm not suggesting we change the admin value as part of the migration... just don't understand why it was set to governance and stuck that way.

In migrating, I standardized it in the pull request with other java contracts... so that admin can be set by governance, governance passed in on constructor sets *governance* and all the state items are gettable. But, like I said, not a strict translation though it should work as the original with the only real exception that admin isn't defaulted on install. But now it can be set. (Note: Loans, for example, sets Admin to Owner on install)

Do you want them strictly like the original in terms of gets and on_install? Do we want it standardized but maybe keep the set admin on install too still just for consistency? 

Note: the very first contract call made was to setGovernance since it was not originally initialized :)

2022-02-15 06:40 UTC, nightowl121 commented
You can add 'gets' as per requirement. There is no secrets to keep in contracts. Even if there are no get methods, analyzing blockchain data will easily provide the db values.

2022-03-05 16:45 UTC, addouglas commented
All existing tests migrated and pass. I noticed that there is not currently a negative rebalance and I've not tried to create such a scenario (yet).

2022-03-16 17:22 UTC, AntonAndell requested changes

2022-03-16 17:24 UTC, AntonAndell commented
> All existing tests migrated and pass. I noticed that there is not currently a negative rebalance and I've not tried to create such a scenario (yet).

Would be nice with test to cover all the cases of re balancing
All 4 paths available here:
   ```
     if (tokenAmount.compareTo(BigInteger.ZERO) == 1) {
            if (higher) {
                Context.call(loansScore, "raisePrice", tokenAmount);
            }
        }
        else {
            if (lower) {
                Context.call(loansScore, "lowerPrice", tokenAmount.abs());
            }
        } 
```

2022-03-18 13:06 UTC, AntonAndell commented
@addouglas  If want some help with evaluating the test you can add jacoo test coverage, so you can see what code you cover int the unit tests. you can see it in the loansContract rewrite or on the bnusd pull request i showed how to add it.

2022-03-24 06:12 UTC, AntonAndell commented on core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing/Rebalancing.java
> +        return _price.multiply(_baseSupply).multiply(_quoteSupply).divide(EXA).sqrt().subtract(_baseSupply);
I kinda get the math now but dont really know a good way to split it

2022-03-24 06:29 UTC, AntonAndell commented
@nightowl121 You taking over this review now? Not the best idea if i review my own changes :slightly_smiling_face: 
Overall i think this contracts is largely ready. No integration tests done but deployment works fine. But as we have said previously it might be better to hold off on integration Testing until we decided on a structure.

Could add a score interface now but just keep it in the Rebalancing directory for now, or do you want to wait with adding interfaces for contracts until later?

2022-03-24 07:15 UTC, nightowl121 commented
Sure @AntonAndell I will take a look from here.

2022-03-24 09:39 UTC, nightowl121 commented on core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing/Rebalancing.java
> +        return price.multiply(baseSupply).multiply(quoteSupply).divide(EXA).sqrt().subtract(baseSupply);
This will produce error whenever the price is negative. Can't calculate square root of negative number.

2022-03-24 12:13 UTC, AntonAndell commented on core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing/Rebalancing.java
> +        return price.multiply(baseSupply).multiply(quoteSupply).divide(EXA).sqrt().subtract(baseSupply);
Yeah saw you changes cleans up nice, it is good the check that the price is not negative since this is a helper function but can it ever be negative?

2022-03-24 16:19 UTC, nightowl121 commented on core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing/Rebalancing.java
> +        return price.multiply(baseSupply).multiply(quoteSupply).divide(EXA).sqrt().subtract(baseSupply);
Oops! got confused with the price difference. Yeah the oracle price can't get negative. I though the price is coming from the difference.

2022-03-29 11:06 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private final MockedStatic<Context> contextMock = Mockito.mockStatic(Context.class, Mockito.CALLS_REAL_METHODS);
Nice! Much better than using mock contracts for unit tests.

2022-03-29 11:08 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private void testContractSettersAndGetters(String setterMethod, Account scoreAddress, String getterMethod) {
Also quite clever, However it does do multiple tests in one but is probably fine in such insignificant tests

2022-03-29 11:15 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +        return Stream.of(BigInteger.TEN.pow(17), BigInteger.TEN.pow(16));
I do not understand why you are testing these thresholds in the rebalance method. Could you explain your choice there? Think not using parameterizing here would make more sense

2022-03-29 11:17 UTC, nightowl121 commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private void testContractSettersAndGetters(String setterMethod, Account scoreAddress, String getterMethod) {
At least better than repeating the code. May be, the tests can be changed to parameterized tests, passing different values we want to test.

2022-03-29 11:18 UTC, nightowl121 commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +        return Stream.of(BigInteger.TEN.pow(17), BigInteger.TEN.pow(16));
These values represent 10% and 1%. There is no specific reason to choose this specific value, can be changed to other better alternatives.

2022-03-29 11:36 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private void testContractSettersAndGetters(String setterMethod, Account scoreAddress, String getterMethod) {
Yeah, get/sets usually get inherently tested during other tests since the are needed to be set anyway, so not something we should spend time on right now perhaps :smile:

2022-03-29 11:39 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +        return Stream.of(BigInteger.TEN.pow(17), BigInteger.TEN.pow(16));
Aah okey then mabye thoose tests can be non parameterized since you have 4 different test doing each case anyway. But doesn't really matter i guess

2022-03-29 13:46 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private final MockedStatic<Context> contextMock = Mockito.mockStatic(Context.class, Mockito.CALLS_REAL_METHODS);
On further thought is this smart in complex contract environments, won't we get more value, especially in large contracts, to use mock contracts? 

This is however further down the line and focus right now should be to get continuous rewards and bBaln running.

But when we have Interfaces of all contracts we could easily implement mocks for each contract. where mock contracts implement both a mock interface and a specific contract interface. Thus changing method names/parameters gets reflected across test and does not get outdated. 
When we do not have to write new mocks whenever we unit test a contract it should not be as a large overhead as it is now. 
So basically when we have interfaces we can create a mock class where are methods are default Implemented.

`public class SomeContractMock extends MockContract implements SomeContractInterface {...}`  

Where you only need to define the constructor for SomeContractMock.

Then have MockContract implement methods such as `Call(Address, method, Object... params)` so you can for example could initiate calls from the contract and other good methods. Have not thought this through completely but not sure mocking context will be sustainable in all contracts

2022-03-29 16:11 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private final MockedStatic<Context> contextMock = Mockito.mockStatic(Context.class, Mockito.CALLS_REAL_METHODS);
Yeah that looks quite handy, gonna investigate contract mocking with scoreClientInterfaces

2022-03-29 18:35 UTC, AntonAndell commented on core-contracts/Rebalancing/src/test/java/network/balanced/score/core/rebalancing/RebalancingTest.java
> +    private final MockedStatic<Context> contextMock = Mockito.mockStatic(Context.class, Mockito.CALLS_REAL_METHODS);
Something like this might be a good replacement once we got interfaces for all contracts.

```
public class MockContract {
    public MockContract() {
    }
}
```

```
SomeScoreClientInterface contractMock = Mockito.mock(SomeScoreClientInterface.class);
Score someContract = sm.deploy(admin, MockContract.class);
someContract.setInstance(contractMock);

// Mock methods
when(contractMock.method()).thenReturn("someValue");

//use Score 
someContract.getAddress();
```

Then if we could abstract it down to some class like

```
MockedContract<SomeScoreClientInterface> someContract = MockedContract.deploy<SomeScoreClientInterface>(sm)
// Inherits Score methods and is mockable
when(someContract.method()).thenReturn("someValue");
someContract.getAddress();
```

This also automatically create default implementations for the interface. So things like 
`contextMock.when(() -> Context.call(eq(loansScore.getAddress()), eq("raisePrice"), any(BigInteger.class))).thenReturn(null); `
are done automatically.

2022-04-05 04:57 UTC, AntonAndell commented
@nightowl121 really like the addition of score-lib and test-lib! we are starting to get some infrastructure in place. How soon do you think we can get it to master? so other devs can use and contribute to it?

Do you need any help here or on the Staking contracts? Since those contain most of the infrastructure it would ease development on other contracts to get it in asap.

2022-04-05 04:57 UTC, AntonAndell commented
@nightowl121 really like the addition of score-lib and test-lib! we are starting to get some infrastructure in place. How soon do you think we can get it to master? so other devs can use and contribute to it?

Do you need any help here or on the Staking contracts? Since those contain most of the infrastructure it would ease development on other contracts to get it in asap.

2022-04-05 06:00 UTC, nightowl121 commented
Rebalancing is ready to be merged to master. 

I would definitely need help in having robust integration test framework, starting from Staking contract.

2022-04-05 06:27 UTC, AntonAndell commented
Sweet then lets merge it soon. I can do a quick review of you recent changes tonight and perhaps merge after that?

I can start looking a bit on the staking contract as well and start to contribute to the infrastructure there as soon as i've done the first draft of the rewards contract. What do you you feel we are missing currently in the staking contracts and what is missing in the integration test framework.

2022-04-05 10:10 UTC, nightowl121 commented
I would consider integration test framework as done if we could run a single command and run all the integration tests automatically. Currently the integration tests is not complete in that regards. It can be run manually though.

Once we have automation in that, we could apply CI for running integration tests in local gochain node. We could run one local gochain node and run our integration tests against it.

2022-04-05 12:09 UTC, nightowl121 commented
> Sweet then lets merge it soon. I can do a quick review of you recent changes tonight and perhaps merge after that?
> 
> I can start looking a bit on the staking contract as well and start to contribute to the infrastructure there as soon as i've done the first draft of the rewards contract. What do you you feel we are missing currently in the staking contracts and what is missing in the integration test framework.

Rebalancing is ready for merge from my side, you may take a look. @AntonAndell

2022-04-05 15:30 UTC, AntonAndell commented
It looks good, but adding a scoreclient interface might be good. I can add and push, it should be quick to write

2022-04-05 15:39 UTC, nightowl121 commented
> It looks good, but adding a scoreclient interface might be good. I can add and push, it should be quick to write

Yeah, Please go ahead.

2022-04-05 16:24 UTC, AntonAndell commented
Done, check that and if u don't see anything super weird, merge it!

checked that all tests pass and deployment to my local node works

2022-04-05 16:24 UTC, AntonAndell commented
Done, check that and if u don't see anything super weird, merge it!

checked that all tests pass and deployment to my local node works

2022-04-05 16:34 UTC, AntonAndell approved these changes

2022-04-05 16:35 UTC, AntonAndell commented
> Did you try keeping this compileOnly and annotation processor?

hmm no i can try it. Which one do we want annotation or compileOnly? or do you need both?

2022-04-05 18:14 UTC, AntonAndell approved these changes

2022-04-05 18:49 UTC, AntonAndell commented
Also changed to Impl naming so when creating interfaces the syntax will be a lot more readable

2022-04-06 11:00 UTC, nightowl121 commented
Moved the interface to score-lib.

2022-04-06 11:06 UTC, nightowl121 approved these changes
Approved

2022-04-06 11:06 UTC, merged