Translation of bnUSD token
balancednetwork/balanced-java-contracts pull request #63
Opened 2022-02-26 02:22 UTC by ZeChosenName

2022-03-18 07:16 UTC, AntonAndell requested changes
Take a look at the offical implementations of IRC2 if you haven't already. https://github.com/sink772/javaee-tokens/find/master
Then since this does not apply fully to all functionalities we need to test the token implementations. 

Also some pointers on code style consistency.
use at max only 1 newline to separate code.
newlines after } unless it is another }
```
if (a) {
     if (b) {
        do x;
    }
}

return x;
```
Only use comment when the code is so bad that it need explanations, and before you add it try to think about how the code can be improved instead. 

Keep up the good work :muscle:  I might be a bit extra hard on testing on this on since this contracts if very bad to bugs in, so try and cover as many cases as possible.

Also if you can try deploying it to find issues such as those with usage of non allowed methods.

Best way to do it is with the esitmate step command, it gives the best error messages.
```
./goloop rpc sendtx deploy /path/to/optimized.jar     --uri http://localhost:9082/api/v3     --key_store godWallet.json --key_password gochain
 --nid 3 --step_limit=100000000     --content_type application/java   --estimate  --param x=y z=u
```

2022-03-18 07:16 UTC, AntonAndell commented on token-contracts/bnUSD/src/test/java/network/balanced/score/tokens/TestBNUSD.java
> +public class TestBNUSD extends TestBase {
Also seem to be a lot of test missing, and i feel we should test all functionality in IRC2 implementations aswell.

2022-03-18 12:53 UTC, AntonAndell commented on token-contracts/bnUSD/build.gradle
> +}
```suggestion
test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport 
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}
```

Add this and then to project gradle add 
`apply plugin: 'jacoco'`
and you can get coverage reports of your unitTests. You wont need a 100% but you can look through there to check you are covering all the good spots :slightly_smiling_face:

2022-03-31 10:12 UTC, Suyog007 commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/tokens/IRC2Mintable.java
> +    }
We need to call _mint(function of IRC2) too .
https://github.com/balancednetwork/balanced-contracts/blob/development/token_contracts/bnUSD/tokens/IRC2mintable.py#L21

2022-03-31 10:19 UTC, Suyog007 commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/tokens/IRC2Mintable.java
> +    public void mintTo(Address _account, BigInteger _amount, @Optional byte[] _data) {
We need to check if the _data we received is null or not just the way we did in above mint function

2022-03-31 10:37 UTC, Suyog007 commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/tokens/IRC2.java
> +    final protected static Address EOA_ZERO = Address.fromString("hx" + zero.repeat(40));
.repeat should be avoided as it will give an issue while converting to jar file. Instead ,we can directly assign hx000.... to a constant.

2022-04-21 13:18 UTC, nightowl121 commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/tokens/TokenStandard.java
> +}
We have implemented our own due to the difference in variable keys name.

2022-04-21 13:18 UTC, nightowl121 commented
@AntonAndell I have updated as per your suggestions. Please check the updated PR. The contract is ready for deployment.

2022-04-21 13:21 UTC, AntonAndell commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/tokens/TokenStandard.java
> +}
Aah, did not notice that

2022-04-21 13:24 UTC, nightowl121 commented on token-contracts/bnUSD/src/main/java/network/balanced/score/tokens/BalancedDollar.java
> +        super(TOKEN_NAME, SYMBOL_NAME, null, null);
Have adjusted all the contracts constructor so that the code is not executed twice during the upgrades.

2022-04-21 16:08 UTC, AntonAndell approved these changes
Overall structure of token implementation looks great now! nice work. 
From quick testing and glance i can't find any functional issues, so looks good to me :+1:  Think in some places we could improve even more on code structure and testing but just minor things which i think we shouldn't put more effort into now since there is a lot more work needed elsewhere.

2022-04-22 08:17 UTC, AntonAndell approved these changes

2022-04-22 08:17 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/tokens/IRC2Burnable.java
> +        burnFrom(Context.getCaller(), _amount);
Just curious, do you how would it affect the system if a asset is burned by a user?

2022-04-22 09:19 UTC, nightowl121 commented on score-lib/src/main/java/network/balanced/score/lib/tokens/IRC2Burnable.java
> +        burnFrom(Context.getCaller(), _amount);
bnUSD is generated by locking icx and getting a debt. If we allow the user's to burn bnusd, the debt position still remains open but there is no bnusd to payback the loan. Similarly in case of icx, if we burn sicx, the ratio of sicx:icx in the contract changes creating unfavorable situations.

2022-04-22 09:38 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/tokens/IRC2Burnable.java
> +        burnFrom(Context.getCaller(), _amount);
Yeah okey it gets a bit weird. Just off the bat burning bnusd seems like it would create a stronger backing. But needs to be handled correctly :+1:

2022-04-25 10:02 UTC, merged