fee handler java translation
balancednetwork/balanced-java-contracts pull request #68
Opened 2022-03-03 11:42 UTC by simusud

fee handler java translation and unit tests

2022-03-16 07:55 UTC, AntonAndell requested changes
Initial review looks good, some mostly minor changes :muscle: . 
Also make sure the rebase on main and use the dependency structure in place there.

Still need to look at the testing, will do that a little later.

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +import static network.balanced.score.core.Checks.onlyGovernance;
import static network.balanced.score.core.Checks.*;

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +
no need for double newlines i think

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            FeeHandler.governance.set(governance);
I perfer usage of this, and i think that is what we are using in other translations

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        if (governance != null) {
Minor thing about this constructor is that you can override the governance parameter by updating the contract. Dont know if this is intended or not. 
But if not id suggest also checking this.governance to see if it is already set.

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            accepted_dividends_tokens.pop();
pop returns the object popped, i think there is a remove Last function as well which does not return the object after each remove.

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        String[] pa = new String[pathJson.size()];
pa is for pathArray? pathArray could be a better name. Might be even better ones, like route, orderdPath, orderdPathArray. You probably have better knowledge for choosing the most correct one or something completely different

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        if (last_txhash.getOrDefault(new byte[0]) == (Context.getTransactionHash())) {
```
        if (last_txhash.getOrDefault(new byte[0]) == (Context.getTransactionHash())) {
            return;
        } else if (!timeForFeeProcessing(sender)) {
            return;
        } 

        last_txhash.set(Context.getTransactionHash());
```

This structure would work as well right?

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        }
space after } is nice :slightly_smiling_face:

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            }
```suggestion
            if (balance.compareTo(BigInteger.ZERO) > 0) {
                break;
            } else  if (loop_flag && (starting_index.equals(current_index))) {
                  Context.revert("No fees on the contract.");
             }
              
              current_index = current_index.add(BigInteger.ONE);
              if (!loop_flag) {
                  loop_flag = true;
              }
```

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            }
else can be removed here also, since both the ifs break execution so we can remove nesting depth by 1.
Also don't use the apply suggestion feature did not do the code properly

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        }
newline

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        } catch (Exception e) {
What are we catching?  Could you explain the usage?
In general we want to avoid caching general Expections since we do not get any information on what goes wrong if something unexpectedly happens in that clause. 

Uncatched exceptions still reverts the transaction so all does not need to be catched.

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            Context.revert("No fees on the contract " + address + " failed" + e.getMessage());
Same here for the try catch, id rather we catch the specific exception that tells us we do not have any fees, and even better use the Context.require to assert the values needed if possible

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        BigInteger blockHeight = BigInteger.valueOf(Context.getBlockHeight());
```suggestion
        }
        
        BigInteger blockHeight = BigInteger.valueOf(Context.getBlockHeight());
```

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            return Boolean.TRUE;
Hmm unsure if this needed, i have not had any problems returning primitives. (true, false). Do you have a difference in behavior using primitives instead?

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +    public byte[] createDataFieldRouter(Address _receiver, JsonArray _path) {
All of these non external functions should probably be made private. Does not really matter but could allow for unrepresentative behavior during testing.

2022-03-16 07:55 UTC, AntonAndell commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/Checks.java
> +}
```suggestion
    }
}
```

2022-03-18 13:05 UTC, AntonAndell commented
@simusud If want some help with evaluating the test you can add jacoo test coverage, so you can see what code you cover int the unit tests. you can see it in the loansContract rewrite or on the bnusd pull request i showed how to add it.

2022-03-21 12:39 UTC, simusud commented
> Initial review looks good, some mostly minor changes 💪 . Also make sure the rebase on main and use the dependency structure in place there.
> 
> Still need to look at the testing, will do that a little later.
> 
> Edit: I do not see a gradle file commited for you contract, did you forget to add it? Will pause review until that is resolved so i can run the code.

sorry about that , i have just uploaded the gradle file and rebased the branched to main.

2022-03-23 12:01 UTC, simusud commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +        } catch (Exception e) {
it was to catch the case when route is empty. But yeah, i have optimized it removing try and catch

2022-03-23 14:31 UTC, simusud commented on core-contracts/feehandler/src/main/java/network/balanced/score/core/FeeHandler.java
> +            Context.revert("No fees on the contract " + address + " failed" + e.getMessage());
Same here, will remove try and catch as it looks unnecessary to catch exception.

2022-03-25 11:25 UTC, simusud commented
Made the requested changes .  Please have a look once .

2022-03-28 18:33 UTC, AntonAndell requested changes
Contract look almost finished, just to comments.

Testing can still be improved i think.
Missing a few test cases and could improve structure a bit. Please just tag me in comments here if you have any questions/don't agree. I usually respond quite quickly.
Try to keep a consistent structure, usually

Setup all you need for the test, variables/contract state

Do something, call methods/transfer tokens

Verify everything relevant, Assert that everything is as it is supposed to be. The correct values are set or the correct methods are called

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +        feehandler.invoke(governance.getAccount(), "deleteRoute",sicxScore.getAddress(), baln.getAddress());
Needs to assert that it is deleted

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +    }
Needs assert, to show what it is testing

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +    }
Assert that the correct contracts are called, id use mockito spy to achieve this.

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +
Add a test for route_contract_balances to check for infinite loops, a list larget than 1 with all balance 0 i think

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +        assertEquals(baln.getAddress(), res.get("toToken"));
Assert the other 2 parameters aswell

2022-03-28 18:33 UTC, AntonAndell commented on core-contracts/feehandler/src/test/java/network/balanced/score/core/feehandler/FeeHandlerTest.java
> +import scorex.util.ArrayList;
U can use java.util.arrayList here

2022-03-29 11:57 UTC, AntonAndell commented
Look at how nightowl use static mock to replace the need to mock normal contracts.
https://github.com/balancednetwork/balanced-java-contracts/pull/54#discussion_r837346066

You can look there to see how you can probably remove the need for a governance mock

2022-04-12 13:58 UTC, AntonAndell commented
Developing now is like constantly developing against a moving target, sorry about that. But if you can please rebase on master, and add a interface to you contract in score-lib, which you then implement in your contract. You can check how it is done for example rebalancing.

2022-04-27 07:23 UTC, nightowl121 commented
@AntonAndell feehandler is ready for merge

2022-04-27 14:47 UTC, AntonAndell approved these changes
Looks good, but admin is used instead of governance in many places. Is that an active choice and if it is are we sure governance is admin on mainnet?

2022-04-27 15:50 UTC, nightowl121 commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        only(admin);
Yeah, only(admin) is an intended choice to bring uniformity with other contracts. Currently admin is not set in mainnet.  It can be set either during upgrade or later through governance contract. All the methods having only(admin) are configuration methods which are already being set in mainnet, so they don't have immediate use also.

2022-04-27 16:01 UTC, AntonAndell commented on core-contracts/FeeHandler/src/main/java/network/balanced/score/core/feehandler/FeeHandlerImpl.java
> +        only(admin);
Sounds good

2022-07-12 05:33 UTC, nightowl121 approved these changes
Approved

2022-07-12 07:01 UTC, nightowl121 approved these changes
Approved

2022-07-12 07:13 UTC, merged