[DEX] Translate DEX into java - WIP
balancednetwork/balanced-java-contracts pull request #78
Opened 2022-04-01 02:36 UTC by gedanziger

This has all of the dex, minus the scorelib dependent parts

2022-05-02 05:43 UTC, AntonAndell commented
Would probably be a good idea here to move to Interfaces and data structures for cross contract calls. Just to verify all the input/output. Did it to Loans and found a few potential bugs.

2022-05-03 06:15 UTC, AntonAndell requested changes
Still have a bit to go through, but for now. Most logic looks fine in a initial look, but sure a few more bugs will come up during unit testing.  But overall looks like really few mistakes translating such a huge contract (jinx inc).
Some general comments on code style:
Try to stick to a code style, there is a mix of require and reverts where requires can be used. Try to use Context.require where it makes sense. 

Alot of comments in the code, most are pretty good and much better than the python ones :smile: But some comments are just repeating what the code says, try to remove those. 

Remove extra parenthesizes for BigInteger operations.

Never use double newline to separate code and a space after nested logic ('}') is usually preferred.

2022-05-03 06:15 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        Map<String, Object> rv = new HashMap<>();
rv for ReturnValue? :smile:  Give it some describing name

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/LinkedListDB.java
> +        }
```suggestion
       Context.require(node.exists() ,"There is no node of the provided node id.");
        node.setValues(size, user);
```

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/LinkedListDB.java
> +        }
```suggestion
        if (size.equals(BigInteger.ONE)) {
            clear();
            return;
        }
 
          NodeDB oldHead = getNode(headId.get());
          BigInteger newHead = oldHead.getNext();
          headId.set(newHead);
          getNode(newHead).setPrev(DEFAULT_NODE_ID);
          oldHead.delete();
          length.set(size.subtract(BigInteger.ONE));
        
```

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/LinkedListDB.java
> +/*
Use requires to remove ifs / nesting.
Remove a lot of double space. 

In general try to keep `else` to a minimum just return in the negative logic ahead of it. Positive logic in else clauses is usually considerd bad practice.

Desired flow of a function is: 

```
if bad: 
    Handle and return
if also bad
    Handle and return
    
Happy logic
```

Where in our cases many if bad can be replaced with Context.require

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/Check.java
> +    public static void isOn(VarDB<Boolean> scoreAddressOn) {
Dex checks should not be in the shared one. Move to the dex package

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/EnumerableSetDB.java
> +        // returns null if value doesn't exist
```suggestion
```

2022-05-04 04:56 UTC, AntonAndell commented on score-lib/src/main/java/network/balanced/score/lib/utils/EnumerableSetDB.java
> +            //add new value
```suggestion
```

2022-05-04 04:56 UTC, AntonAndell commented on token-contracts/sicx/src/main/java/network/balanced/score/tokens/sicx/SicxImpl.java
> +package network.balanced.score.tokens.sicx;
Why is sICX token inculded in this PR? should we ignore it?

2022-05-04 04:56 UTC, AntonAndell commented on core-contracts/Dex/src/test/java/network/balanced/score/core/dex/DexImplTest.java
> +public class DexImplTest extends TestBase {
Tests looking really well structured so far :+1: 

```suggestion
import network.balanced.score.lib.test.UnitTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;


public class DexImplTest extends UnitTest {
```

2022-05-10 09:22 UTC, simusud commented
After updating java contracts getNamedPools seems to be reset, it is returning empty list although there are 3 named pools.

<img width="342" alt="Screen Shot 2022-05-10 at 15 01 52" src="https://user-images.githubusercontent.com/60603625/167595164-9d65c830-4547-4588-8fe0-c6b3c1a81163.png">

2022-05-14 22:05 UTC, Skyvell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +    }
What is the use of this method? It's essentially the same as totalSupply. _snapshot_id is never used.

2022-05-16 05:52 UTC, nightowl121 commented on score-lib/src/main/java/network/balanced/score/lib/utils/NodeDB.java
> +        this.user = Context.newVarDB(name + "_user", Address.class);
Lets not change this parameter here as this linked list db is already used by another score with this key. If dex needs another db with different keys, lets create a new one.

2022-05-16 05:53 UTC, nightowl121 commented on score-lib/src/test/java/network/balanced/score/lib/TestHelper.java
> +}
This is already available in test-lib. Let's not duplicate the code.

2022-05-17 14:06 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        JsonObject params = json.get("params").asObject();
This fails if params are not supplied, only fetch in swap

2022-05-17 14:08 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +            Context.require((poolBaseAddress == _baseToken) && (poolQuoteAddress == _quoteToken), TAG + ": Must supply " + _baseToken.toString() + " as base and " + _quoteToken.toString() + " as quot
use equals instead of ==

2022-05-18 11:03 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (_governance != null) {
check if governance is already set instead. Don't think we wanna rerun this code after inital deployment

2022-05-18 11:04 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +            BigInteger totalSupply = (BigInteger) Context.call(stakedlp.get(), "totalSupply", poolId);
Method in stakedLP is "totalStaked"

2022-05-18 11:05 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        }
We need something like this to take into account stakedLP balance before migration
```suggestion
        } else {
            BigInteger balance = this.balance.at(_id).getOrDefault(_owner, BigInteger.ZERO);
            if (getDay().compareTo(continuousRewardsDay.get()) <= 0) {
                BigInteger stakedBalance = (BigInteger) Context.call(stakedlp.get(), "balanceOf", _owner, poolId);
                balance = balance.add(stakedBalance);
            }
            
            return balance;
    }
```

2022-05-19 05:18 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        }
Investigate that what changes are needed for sicx/icx pool

2022-05-19 12:34 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        return restrictedPoolId && continuousRewardsLaunched;
```suggestion
        return restrictedPoolId && !continuousRewardsLaunched;
```

2022-05-20 04:42 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        return restrictedPoolId && continuousRewardsLaunched;
@nightowl121 Realised this wont be enough. We wanna transfer LP tokens before rewards. Perhaps change the check here to see if stakedLP address is set or just allow transfers from when this contract is deployed? 

But we do wanna restrict on icx/sicx id right?

2022-05-20 10:11 UTC, simusud commented
Some conditions not handled in:
 balanceOfAt in all pool ids : 
<img width="1020" alt="Screen Shot 2022-05-20 at 15 47 58" src="https://user-images.githubusercontent.com/60603625/169505390-2ff1a3c0-c71e-4fff-8e14-444b91d878c8.png">

totalSupplyAt in pool id 1:
<img width="997" alt="Screen Shot 2022-05-20 at 15 51 37" src="https://user-images.githubusercontent.com/60603625/169505859-09257d2a-acbf-4812-b2b8-1d71f4e19029.png">

totalBalnAt in pool id 1 and 2:
<img width="989" alt="Screen Shot 2022-05-20 at 15 52 52" src="https://user-images.githubusercontent.com/60603625/169506084-a6b4ebe8-3f90-428d-b82a-e0de78842293.png">

Contract address on berlin test net :https://berlin.tracker.solidwallet.io/contract/cxd12d5b4afdde9199bcfd8ac39cf2f3c15cc7c376#readcontract

2022-05-23 05:57 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if ((to.isContract()) && (to.equals(stakedlp.get()))) {
"to.equals(stakedlp.get())" why is this added?

2022-05-23 06:10 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
How will unstaking be handled here?

2022-05-23 07:06 UTC, Suyog007 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if ((to.isContract()) && (to.equals(stakedlp.get()))) {
to verify the transfer is being done to the right contract.

2022-05-23 07:07 UTC, Suyog007 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
not sure, if i get your question correctly but unstaking will be handled on stakedLp contract.

2022-05-23 08:19 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
We will change active addresses when some1 unstakes, but not when they stake.  Just worried it might cause problems. The unstake call in stapedlp uses this transfer function

2022-05-23 08:24 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if ((to.isContract()) && (to.equals(stakedlp.get()))) {
Irc31 is a Standard and this breaks it. My guess other contracts like the omm LP contract expects this function to be called when they transfer tokens to their contract

2022-05-23 13:56 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +                minimumReceive = BigInteger.valueOf(params.get("minimumReceive").asInt());
Rebase on main and use convertToNumber helper to avoid errors when fetching from JSON

2022-05-23 19:16 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        Context.call(toToken, "transfer", Context.getAddress(), sendAmount, null);
This send back to the dex contract, should it not be the sender?

2022-05-24 04:19 UTC, Suyog007 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        Context.call(toToken, "transfer", Context.getAddress(), sendAmount, null);
yes that was supposed to be receiver from the param.. Great catch . Thanks

2022-05-24 04:27 UTC, Suyog007 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
yes, but the use of activeaddresses is only on getDataBatch function of dex. so i don't think changing on activeaddresses will interrupt the stakedLp flows.

2022-05-24 06:03 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
Yeah agree there, as long as there are no error trying to remove a adress that does not exist and adding one that already does. 
Stake: nothing changes
Unstake: remove stakelp from active, add user to active

2022-05-24 06:04 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        if (!to.equals(stakedlp.get())) {
Might be enough to just have if not to or from is stakedlp

2022-05-24 10:43 UTC, nightowl121 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +        return restrictedPoolId && continuousRewardsLaunched;
I think should be checking if staked lp address is set or not.

2022-05-25 03:15 UTC, Suyog007 commented
> Some conditions not handled in: balanceOfAt in all pool ids : <img alt="Screen Shot 2022-05-20 at 15 47 58" width="1020" src="https://user-images.githubusercontent.com/60603625/169505390-2ff1a3c0-c71e-4fff-8e14-444b91d878c8.png">
> 
> totalSupplyAt in pool id 1: <img alt="Screen Shot 2022-05-20 at 15 51 37" width="997" src="https://user-images.githubusercontent.com/60603625/169505859-09257d2a-acbf-4812-b2b8-1d71f4e19029.png">
> 
> totalBalnAt in pool id 1 and 2: <img alt="Screen Shot 2022-05-20 at 15 52 52" width="989" src="https://user-images.githubusercontent.com/60603625/169506084-a6b4ebe8-3f90-428d-b82a-e0de78842293.png">
> 
> Contract address on berlin test net :https://berlin.tracker.solidwallet.io/contract/cxd12d5b4afdde9199bcfd8ac39cf2f3c15cc7c376#readcontract

@simusud  the changes for this issue is already pushed . this is now working right?

2022-05-25 09:12 UTC, AntonAndell commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +            snapshotBalance = snapshotBalance.add(stakedBalance);
This is done in the above balanceOf so this should be removed

2022-05-25 09:27 UTC, nightowl121 commented on token-contracts/sicx/src/main/java/network/balanced/score/tokens/sicx/SicxImpl.java
> +package network.balanced.score.tokens.sicx;
This should be removed from this PR.

2022-05-28 13:29 UTC, nightowl121 commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/DexImpl.java
> +    }
Yeah should be removed as parameter and may be use another getTotalValueAt method.

2022-06-02 10:53 UTC, simusud commented on core-contracts/Dex/src/main/java/network/balanced/score/core/dex/AbstractDex.java
> +        Context.require(!isLockingPool(id), TAG + ": Nontransferable token id");
We need to move this line to the beginning of the method. If the the token is non transferable we will be getting "Out of balance" revert msg.

2022-06-06 08:26 UTC, AntonAndell commented
U_SECONDS_DAY seems to be off? are they changed for integrationTest or something?

2022-06-10 14:03 UTC, AntonAndell commented
@gedanziger was this way of calculating done for any special reason?
https://github.com/balancednetwork/balanced-contracts/blob/cd185fa831de18b4d9c634689a3c6e7b559bbabe/core_contracts/dex/dex.py#L1021

int(self._pool_total[_id][_fromToken] * self._pool_total[_id][_toToken] / new_token1)
gives somewhat significant difference from:
(self._pool_total[_id][_fromToken] * self._pool_total[_id][_toToken]) // new_token1

what we have in java is more aligned with the second way of doing it.

2022-06-16 15:38 UTC, merged