Dividends java translation
balancednetwork/balanced-java-contracts pull request #86
Opened 2022-04-15 08:33 UTC by simusud

translated dividends to java

2022-04-16 07:09 UTC, AntonAndell requested changes
Most functionality seems to be correct just found a few mistakes, good work.
The code is very inconsistently mixed with java and python variable naming standard.
Use python only in input variables to external functions. Also for strings used as keys to Maps shared between contracts. For all non external functions and internal variables use java naming convention.

Only use String.valueOf if .toString() is not available (which probably will be never :smile: )

Testing looks good.
dividendsAt has a quite complicated search logic which i believe deserves a test case even though it requires quite a lot of setup to arrive at. 

Extend you UnitTest class with the one in testLib and you can remove some base logic. Check out what helpers exists and use them where you can.

2022-04-16 09:11 UTC, nightowl121 commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +            if (balance.compareTo(BigInteger.ZERO) > 0) {
Usually IDE suggests to keep with 0 comparison here. The reason to keep zero comparison is that by keeping zero, the sign of comparison is exactly the same written as in code.

Like, balance.compareTo(BigInteger.ZERO) > 0 can be easily replaced with
balance > BigInteger.ZERO. So it's better to keep comparison with zero, so that the comparison sign is same while reading the code.

2022-04-16 09:47 UTC, AntonAndell commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +            if (balance.compareTo(BigInteger.ZERO) > 0) {
Makes sense, thanks

2022-05-02 15:48 UTC, ZeChosenName commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        }
https://github.com/balancednetwork/balanced-java-contracts/blob/058483d76b7a3e48b6e0f845ad465122e5889f92/core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java#L342
Here the argument should be optional as it is a default argument in python contract 
![image](https://user-images.githubusercontent.com/98825512/166263862-c663582e-875e-4c34-92a3-ef7e07609316.png)

2022-05-06 14:38 UTC, ZeChosenName commented
https://github.com/balancednetwork/balanced-java-contracts/blob/058483d76b7a3e48b6e0f845ad465122e5889f92/core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java#L342
Here the argument should be optional as it is a default argument in python contract 
![image](https://user-images.githubusercontent.com/98825512/166263862-c663582e-875e-4c34-92a3-ef7e07609316.png)

2022-05-09 05:08 UTC, AntonAndell commented
@Suyog007 Saw that you merged in the integration test branch, throw a little review on that PR also with some feedback so we cant get a first version of the integration testing lib to master

2022-05-30 12:34 UTC, AntonAndell commented
@Suyog007 
What do i need to setup to run the integrationTests?

2022-05-31 00:26 UTC, Suyog007 commented
> @Suyog007 What do i need to setup to run the integrationTests?

There are few things that you need to do before running the tests .

1.  set   distributionActivate.set(true); in dividendsImpl constructor.
2. addDividendsCategory(), removeDividendsCategory(), setDividendsCategoryPercentage() should be decorated with onlyOwner instead of onlyAdmin .
3. the time should be reduced on the const.py of each zip file that have day as 86400 * 10**6  . It can be replaced to 100*10**6. And same goes with the dividends const too.

2022-05-31 16:22 UTC, nightowl121 commented on core-contracts/Dividends/src/main/java/network/balanced/score/core/dividends/DividendsImpl.java
> +        }
This portion is removed so now no removal of zero values. This output is further used in another method where it would get 0 value.

2022-06-01 16:40 UTC, ajaya-man approved these changes

2022-06-01 16:43 UTC, merged