added safe math method for calculation
balancednetwork/balanced-java-contracts pull request #9
Opened 2022-01-12 07:38 UTC by redlarva

2022-01-12 17:10 UTC, AntonAndell commented on token-contracts/bBaln/src/test/java/network/balanced/score/tokens/StateMachineTest.java
> +
remove

2022-01-12 17:10 UTC, AntonAndell commented on token-contracts/bBaln/src/test/java/network/balanced/score/tokens/StateMachineTest.java
> +
remove

2022-01-12 17:10 UTC, AntonAndell commented on token-contracts/bBaln/src/test/java/network/balanced/score/tokens/StateMachineTest.java
> +            Executable actualErrorMessage = () ->
"actualErrorMessage" kinda makes sense but everywhere else the all called after the actual call. 
The function expectErrorMessage might sound misleading, mabye that was a poor choice by me. If you can think of a better name please change it.

I wanted it to read like "expect Error Message from call equal to error message"
expectErrorMessage(method, errorMessage)

2022-01-13 11:59 UTC, nightowl121 requested changes
Block height, timestamp and supply can't be negative, so I would suggest to implement safesubtract in all the subtraction related to these variables.

2022-01-13 11:59 UTC, nightowl121 commented on token-contracts/bBaln/src/main/java/network/balanced/score/tokens/utils/MathUtils.java
> +                    "MathUtils.SafeSubtract :: Invalid operation");
I would suggest the error message to be changed to ""MathUtils.SafeSubtract :: Invalid operation for unsigned numbers" since the error is more focused on getting signed number from the subtraction of two numbers which needs to be unsigned.

2022-07-11 08:51 UTC, nightowl121 commented
The intended changes from this PR is already included in the boosted baln branch.

2022-07-11 08:51 UTC, closed without merging