88 set up of testnet env with single click
balancednetwork/balanced-java-contracts pull request #98
Opened 2022-05-07 11:53 UTC by AntonAndell

Beginning of a integration testing framework running on a local node.

2022-05-09 06:02 UTC, nightowl121 requested changes

2022-05-09 06:05 UTC, AntonAndell commented on .gitignore
> +!integrationtest-lib/python-contracts/*.zip
Lol goddam, Move the files into the testlib and forgot the git ignore. Im no home until tonight. If you checkout the first commit they should be there. If you want you can add them and push them up

2022-05-09 06:08 UTC, AntonAndell commented on test-lib/src/main/java/network/balanced/score/lib/test/integration/Balanced.java
> +}
Im thinking of splitting the balanced methods a lot more. So you can deconstruct it however you want to. But thinking we will do this when we are hands on with testing. Will be much easier to find the correct solutions then

2022-05-09 06:37 UTC, AntonAndell commented on .gitignore
> +!integrationtest-lib/python-contracts/*.zip
nvm they aren't there either

2022-05-09 09:52 UTC, Suyog007 commented on test-lib/src/main/java/network/balanced/score/lib/test/integration/Balanced.java
> +        sicx = deploy(owner, "Sicx", Map.of("_admin", governance._address()));
admin of sicx will be staking address not governance

2022-05-12 04:49 UTC, nightowl121 approved these changes

2022-05-12 04:49 UTC, merged